
#### CREATE USER ENDPOINT
POST {{local}}/api/users
Content-Type: application/json

{
  "email" : "qq@ahsraf.com",
  "username"  : "qq"
}


#### LOGIN USER ENDPOINT
POST {{local}}/api/login
Content-Type: application/json

{
  "email" : "rr@ahsraf.com"
}


#### GET AUTH USER ENDPOINT
GET {{local}}/api/auth_user
Authorization: {{user-token}}



#### TOGGLE FOLLOW ENDPOINT
POST {{local}}/api/users/qq/toggle_follow
Authorization: {{user-token}}



#### GET USER PROFILE ENDPOINT
GET {{local}}/api/users/qq
Authorization: {{user-token}}



#### GET ALL USERS WITH FILTERS username ENDPOINT
GET {{local}}/api/users?search=&first=&after=
Authorization: {{user-token}}
