
#### CREATE USER ENDPOINT
POST {{local}}/api/users
Content-Type: application/json

{
  "email" : "test@ahsraf.com",
  "username"  : "test"
}


#### LOGIN USER ENDPOINT
POST {{local}}/api/login
Content-Type: application/json

{
  "email" : "youssef@youssef.com"
}


#### GET AUTH USER ENDPOINT
GET {{local}}/api/auth_user
Authorization: {{user-token}}



#### PUT AVATAR FOR AUTH USER ENDPOINT
PUT {{local}}/api/auth_user/avatar
Authorization: {{user-token}}
Content-Type: image/png

< assets/test.png


#### TOGGLE FOLLOW ENDPOINT
POST {{local}}/api/users/youssef/toggle_follow
Authorization: {{user-token}}



#### GET USER PROFILE ENDPOINT
GET {{local}}/api/users/joejoe
Authorization: {{user-token}}



#### GET ALL USERS WITH FILTERS username ENDPOINT
GET {{local}}/api/users?search=&first=&after=
Authorization: {{user-token}}



#### GET Follower users ENDPOINT
GET {{local}}/api/users/test/get_followers?first=&after=
Authorization: {{user-token}}



#### GET Followees users ENDPOINT
GET {{local}}/api/users/rr/get_followees?first=&after=
Authorization: {{user-token}}


#### POST CREATE POST ENDPOINT
POST {{local}}/api/posts
Authorization: {{user-token}}
Content-Type: application/json

{
  "content": "new post",
  "spoilerOf": "show name her",
  "nsfw": true
}