

POST {{local}}/api/users
Content-Type: application/json

{
  "email" : "joe@joe.com",
  "username"  : "youssef"
}

###

POST {{local}}/api/login
Content-Type: application/json

{
  "email" : "joe@joe.com"
}

###

GET {{local}}/api/auth_user
Authorization: {{user-token}}